gems: [jekyll-paginate]
# Site settings
title: Metin Balaban Homepage
email: balabanmetin@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Metin Balaban's homepage.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "balabanmetin.github.io" # the base hostname & protocol for your site
twitter_username: balabanmetin
github_username:  balabanmetin

# paginate settings
paginate: 5
paginate_path: "/blog/page:num"

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass

# header-img: "images/Pensieve2.jpg"
